### ISSUE TITLE
cfgo organisation

### ISSUE THREAD

**Issue by TFcfgo** [bleau2/CFGO.github.io#1]
Hey,
sorry to disturb on this way, I only have a quick question.
We are a young startup from Germany - CFgO - the CFO to Go. We manage liquidity for SMEs with an automated software. If you like, have a look: https://cfgo.de/

At the moment we are growing and considered managing our projects from now on with a GitHub organisation.
Unfortunately we found that the name CFGO is already taken. Is there any chance considering changing your name? 

This would mean a lot for us!

**Comment by bleau2** [comment]
Hey Thomas,

I am happy to let you have the name.

If i ever start a business in Germany I expect a discount for your services!

Regards,

Carl

**Comment by TFcfgo** [comment]
Hey Carl,

for sure, thanks!!

Best regards
Thomas
